import { createRunWorkspace } from "@/lib/run-store";
import type { ProductionPackage, SourceVideo } from "@/lib/runs";

export type CreateRunInput = {
  topic: string;
  category?: string;
  format?: string;
  language?: string;
  targetAudience?: string;
  tone?: string;
  durationSeconds?: number;
  seedUrls: string[];
};

function slugify(value: string) {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return (slug || "run").slice(0, 48);
}

function extractYouTubeVideoId(url: string) {
  try {
    const parsed = new URL(url);
    const host = parsed.hostname.toLowerCase().replace(/^www\./, "");

    if (host === "youtu.be") {
      return parsed.pathname.replace(/^\/+/, "").split("/")[0] ?? "";
    }

    if (host.endsWith("youtube.com")) {
      const queryVideoId = parsed.searchParams.get("v");
      if (queryVideoId) {
        return queryVideoId;
      }

      const parts = parsed.pathname.split("/").filter(Boolean);
      for (const marker of ["shorts", "embed", "live"]) {
        const index = parts.indexOf(marker);
        if (index >= 0 && parts[index + 1]) {
          return parts[index + 1];
        }
      }
    }
  } catch {
    return "";
  }

  return "";
}

function markdownTable(headers: string[], rows: string[][]) {
  const lines = [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
  ];

  for (const row of rows) {
    lines.push(`| ${row.map((cell) => cell.replace(/\n/g, " ").replace(/\|/g, "\\|")).join(" | ")} |`);
  }

  return lines.join("\n");
}

function buildSource(seedUrl: string, index: number): SourceVideo {
  const videoId = extractYouTubeVideoId(seedUrl);
  return {
    rank: index,
    url: seedUrl,
    title: `Manual seed ${index}: ${videoId || seedUrl}`,
    channel: "",
    inclusion_reason: "Manual seed URL provided during intake.",
    transcript_status: "not_checked",
    video_id: videoId,
  };
}

function buildPackage(input: Required<CreateRunInput>, runId: string, sources: SourceVideo[]) {
  const pkg: ProductionPackage = {
    run_id: runId,
    brief: {
      topic: input.topic,
      category: input.category,
      format: input.format,
      target_audience: input.targetAudience,
      target_duration_seconds: input.durationSeconds,
      language: input.language,
      tone: input.tone,
    },
    sources,
    claim_ledger: [],
    script_plan: {
      angle: "Needs strategy selection after research and analysis.",
      hook: "Needs hook drafting after competitor analysis.",
      outline: [
        "Research intake created.",
        "Analyze seed videos.",
        "Fact-check claims.",
        "Draft source-backed script plan.",
      ],
      notes: "Generated by dashboard manual-seed bootstrap. Fill with youtube-script-architect after research and fact-checking.",
    },
    storyboard: [],
    media_prompts: {
      style_bible: "",
      image_prompts: [],
      video_prompts: [],
    },
    publishing_package: {
      title_candidates: [],
      description: "",
      tags: [],
      thumbnail_prompt: "",
    },
    qa: {
      status: "needs_review",
      blockers: [
        "Competitor video analysis is not complete.",
        "Claim ledger is empty.",
        "Script plan is only a bootstrap placeholder.",
        "Storyboard and media prompts are not complete.",
        "Human approval is required before generation or publishing.",
      ],
      approval_required: true,
    },
  };

  return pkg;
}

function jsonContent(payload: unknown) {
  return `${JSON.stringify(payload, null, 2)}\n`;
}

function buildMarkdownFiles(pkg: ProductionPackage): Record<string, string> {
  const brief = pkg.brief;
  const sourceTable = markdownTable(
    ["Rank", "URL", "Video ID", "Working Title", "Reason", "Transcript"],
    pkg.sources.map((source, index) => [
      String(source.rank ?? index + 1),
      source.url,
      source.video_id ?? "",
      source.title,
      source.inclusion_reason,
      source.transcript_status ?? "not_checked",
    ]),
  );

  const files: Record<string, string> = {
    "README.md": `# Run ${pkg.run_id}

## Brief

- Topic: ${brief.topic}
- Category: ${brief.category ?? ""}
- Format: ${brief.format}
- Target audience: ${brief.target_audience ?? ""}
- Target duration: ${brief.target_duration_seconds ?? ""} seconds
- Language: ${brief.language}
- Tone: ${brief.tone ?? ""}

## Stage Checklist

- [x] Intake created
- [ ] Research enriched
- [ ] Source video analysis complete
- [ ] Fact-check complete
- [ ] Script plan approved
- [ ] Storyboard approved
- [ ] Media prompts approved
- [ ] Generation approved
- [ ] Publishing package approved
`,
    "01-research.md": `# 01 Research

## Source Videos

${sourceTable}

## Research Summary

Pending.

## Patterns To Investigate

- Opening hooks
- Thumbnail/title promise
- Retention devices
- Repeated claims
- Viewer payoff
`,
  };

  const placeholders: Array<[string, string]> = [
    ["02-video-analysis.md", "# 02 Video Analysis\n\nPending.\n"],
    [
      "03-claim-ledger.md",
      "# 03 Claim Ledger\n\n| Claim | Status | Evidence URL | Confidence | Action |\n| --- | --- | --- | --- | --- |\n",
    ],
    ["04-script-plan.md", "# 04 Script Plan\n\nPending.\n"],
    [
      "05-storyboard.md",
      "# 05 Storyboard\n\n| Scene | Time | Narration | Visual | On-Screen Text | Asset Needs | Notes |\n| --- | --- | --- | --- | --- | --- | --- |\n",
    ],
    ["06-media-prompts.md", "# 06 Media Prompts\n\nPending.\n"],
    ["07-publishing-package.md", "# 07 Publishing Package\n\nPending.\n"],
    ["08-qa.md", "# 08 QA\n\n## QA Status\n\nneeds_review\n"],
  ];

  for (const [filename, content] of placeholders) {
    files[filename] = content;
  }

  return files;
}

export async function createRun(input: CreateRunInput) {
  const normalized: Required<CreateRunInput> = {
    topic: input.topic.trim(),
    category: input.category?.trim() ?? "",
    format: input.format?.trim() || "shorts",
    language: input.language?.trim() || "ko",
    targetAudience: input.targetAudience?.trim() ?? "",
    tone: input.tone?.trim() ?? "",
    durationSeconds: input.durationSeconds && input.durationSeconds > 0 ? input.durationSeconds : 60,
    seedUrls: input.seedUrls.map((url) => url.trim()).filter(Boolean),
  };

  if (!normalized.topic) {
    throw new Error("Topic is required.");
  }
  if (normalized.seedUrls.length === 0) {
    throw new Error("At least one seed URL is required.");
  }

  const now = new Date();
  const timestamp = [
    now.getFullYear(),
    String(now.getMonth() + 1).padStart(2, "0"),
    String(now.getDate()).padStart(2, "0"),
    "-",
    String(now.getHours()).padStart(2, "0"),
    String(now.getMinutes()).padStart(2, "0"),
    String(now.getSeconds()).padStart(2, "0"),
  ].join("");
  const runId = `${timestamp}-${slugify(normalized.topic)}`;
  const sources = normalized.seedUrls.map((url, index) => buildSource(url, index + 1));
  const pkg = buildPackage(normalized, runId, sources);
  const manifest = {
    run_id: runId,
    created_at: now.toISOString(),
    source_mode: "manual_seed",
    status: "needs_review",
    paths: {
      production_package: "production-package.json",
      brief: "brief.json",
      sources: "sources.json",
      qa: "08-qa.md",
    },
    next_actions: [
      "Enrich research with youtube-market-research.",
      "Analyze source videos with youtube-video-analysis.",
      "Build claim ledger with youtube-fact-check.",
      "Draft script plan with youtube-script-architect.",
    ],
  };

  return createRunWorkspace({
    createdAt: now.toISOString(),
    files: {
      "manifest.json": jsonContent(manifest),
      "brief.json": jsonContent(pkg.brief),
      "sources.json": jsonContent(sources),
      "production-package.json": jsonContent(pkg),
      ...buildMarkdownFiles(pkg),
    },
    id: runId,
    package: pkg,
    status: "needs_review",
  });
}
