#!/usr/bin/env python3
"""Create a manual-seed YouTube production run package."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import parse_qs, urlparse


ROOT = Path(__file__).resolve().parents[1]


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value[:48] or "run"


def extract_youtube_video_id(url: str) -> str:
    parsed = urlparse(url)
    host = parsed.netloc.lower().replace("www.", "")

    if host == "youtu.be":
        return parsed.path.strip("/").split("/")[0]

    if host.endswith("youtube.com"):
        query_video_id = parse_qs(parsed.query).get("v")
        if query_video_id:
            return query_video_id[0]

        parts = [part for part in parsed.path.split("/") if part]
        for marker in ("shorts", "embed", "live"):
            if marker in parts:
                index = parts.index(marker)
                if len(parts) > index + 1:
                    return parts[index + 1]

    return ""


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def build_source(seed_url: str, index: int) -> dict:
    video_id = extract_youtube_video_id(seed_url)
    title_suffix = video_id if video_id else seed_url
    return {
        "rank": index,
        "url": seed_url,
        "title": f"Manual seed {index}: {title_suffix}",
        "channel": "",
        "inclusion_reason": "Manual seed URL provided during intake.",
        "transcript_status": "not_checked",
        "video_id": video_id,
        "source_mode": "manual_seed",
    }


def build_package(args: argparse.Namespace, run_id: str, sources: list[dict]) -> dict:
    return {
        "run_id": run_id,
        "brief": {
            "topic": args.topic,
            "category": args.category or "",
            "format": args.format,
            "target_audience": args.target_audience or "",
            "target_duration_seconds": args.duration_seconds,
            "language": args.language,
            "tone": args.tone or "",
        },
        "sources": sources,
        "claim_ledger": [],
        "script_plan": {
            "angle": "Needs strategy selection after research and analysis.",
            "hook": "Needs hook drafting after competitor analysis.",
            "outline": [
                "Research intake created.",
                "Analyze seed videos.",
                "Fact-check claims.",
                "Draft source-backed script plan.",
            ],
            "notes": "Generated by manual-seed Phase 1 bootstrap. Fill with youtube-script-architect after research and fact-checking.",
        },
        "storyboard": [],
        "media_prompts": {
            "style_bible": "",
            "image_prompts": [],
            "video_prompts": [],
        },
        "publishing_package": {
            "title_candidates": [],
            "description": "",
            "tags": [],
            "thumbnail_prompt": "",
        },
        "qa": {
            "status": "needs_review",
            "blockers": [
                "Competitor video analysis is not complete.",
                "Claim ledger is empty.",
                "Script plan is only a bootstrap placeholder.",
                "Storyboard and media prompts are not complete.",
                "Human approval is required before generation or publishing.",
            ],
            "approval_required": True,
        },
    }


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        escaped = [cell.replace("\n", " ").replace("|", "\\|") for cell in row]
        lines.append("| " + " | ".join(escaped) + " |")
    return "\n".join(lines)


def write_json(path: Path, payload: object) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_markdown_files(run_dir: Path, package: dict) -> None:
    brief = package["brief"]
    sources = package["sources"]

    source_rows = [
        [
            str(source["rank"]),
            source["url"],
            source.get("video_id", ""),
            source["title"],
            source["inclusion_reason"],
            source["transcript_status"],
        ]
        for source in sources
    ]
    source_table = markdown_table(
        ["Rank", "URL", "Video ID", "Working Title", "Reason", "Transcript"],
        source_rows,
    )

    (run_dir / "README.md").write_text(
        f"""# Run {package["run_id"]}

## Brief

- Topic: {brief["topic"]}
- Category: {brief.get("category", "")}
- Format: {brief["format"]}
- Target audience: {brief.get("target_audience", "")}
- Target duration: {brief.get("target_duration_seconds", "")} seconds
- Language: {brief["language"]}
- Tone: {brief.get("tone", "")}

## Stage Checklist

- [x] Intake created
- [ ] Research enriched
- [ ] Source video analysis complete
- [ ] Fact-check complete
- [ ] Script plan approved
- [ ] Storyboard approved
- [ ] Media prompts approved
- [ ] Generation approved
- [ ] Publishing package approved

## Next Skills

1. `youtube-market-research`
2. `youtube-video-analysis`
3. `youtube-fact-check`
4. `youtube-script-architect`
5. `youtube-storyboard`
6. `youtube-media-prompts`
7. `youtube-production-qa`
""",
        encoding="utf-8",
    )

    (run_dir / "01-research.md").write_text(
        f"""# 01 Research

## Source Videos

{source_table}

## Research Summary

Pending. Use `youtube-market-research` to enrich this section.

## Patterns To Investigate

- Opening hooks
- Thumbnail/title promise
- Retention devices
- Repeated claims
- Viewer payoff
""",
        encoding="utf-8",
    )

    (run_dir / "02-video-analysis.md").write_text(
        """# 02 Video Analysis

Use `youtube-video-analysis` to fill one compact card per source video.

## Per-Video Analysis

Pending.

## Hook Library

Pending.

## Structure Patterns

Pending.

## Claim Candidates

Pending.
""",
        encoding="utf-8",
    )

    (run_dir / "03-claim-ledger.md").write_text(
        """# 03 Claim Ledger

Use `youtube-fact-check` to classify claims.

| Claim | Status | Evidence URL | Confidence | Action |
| --- | --- | --- | --- | --- |

Allowed statuses: `supported`, `needs_evidence`, `opinion`, `high_risk`, `do_not_use`.
""",
        encoding="utf-8",
    )

    (run_dir / "04-script-plan.md").write_text(
        """# 04 Script Plan

Use `youtube-script-architect` after analysis and fact-checking.

## Strategy

Pending.

## Hook Options

Pending.

## Beat Map

Pending.

## Narration Draft

Pending.
""",
        encoding="utf-8",
    )

    (run_dir / "05-storyboard.md").write_text(
        """# 05 Storyboard

Use `youtube-storyboard` after the script plan is approved.

| Scene | Time | Narration | Visual | On-Screen Text | Asset Needs | Notes |
| --- | --- | --- | --- | --- | --- | --- |
""",
        encoding="utf-8",
    )

    (run_dir / "06-media-prompts.md").write_text(
        """# 06 Media Prompts

Use `youtube-media-prompts` after storyboard approval.

## Style Bible

Pending.

## Image Prompts

Pending.

## Video Prompts

Pending.

## Thumbnail Prompts

Pending.
""",
        encoding="utf-8",
    )

    (run_dir / "07-publishing-package.md").write_text(
        """# 07 Publishing Package

## Title Candidates

Pending.

## Description

Pending.

## Tags

Pending.

## Thumbnail

Pending.

## Upload Checklist

- [ ] Final render reviewed
- [ ] Captions reviewed
- [ ] Rights/provenance checked
- [ ] Human approval granted
""",
        encoding="utf-8",
    )

    (run_dir / "08-qa.md").write_text(
        """# 08 QA

Use `youtube-production-qa` before paid generation, final render, or publishing.

## QA Status

needs_review

## Blockers

- Competitor video analysis is not complete.
- Claim ledger is empty.
- Script plan is only a bootstrap placeholder.
- Storyboard and media prompts are not complete.
- Human approval is required before generation or publishing.
""",
        encoding="utf-8",
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a manual-seed YouTube production run package."
    )
    parser.add_argument("--topic", required=True, help="Topic or idea for the run.")
    parser.add_argument("--category", default="", help="YouTube category or niche.")
    parser.add_argument("--format", default="shorts", help="shorts, long-form, explainer, etc.")
    parser.add_argument("--language", default="ko", help="Primary script language.")
    parser.add_argument("--target-audience", default="", help="Target viewer segment.")
    parser.add_argument("--tone", default="", help="Channel tone or style.")
    parser.add_argument(
        "--duration-seconds",
        type=int,
        default=60,
        help="Target duration in seconds.",
    )
    parser.add_argument(
        "--seed-url",
        action="append",
        default=[],
        help="Manual YouTube source URL. Repeat for multiple seeds.",
    )
    parser.add_argument("--run-id", default="", help="Optional explicit run id.")
    parser.add_argument(
        "--output-dir",
        default=str(ROOT / "runs"),
        help="Directory where run folders are created.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing run folder.")
    args = parser.parse_args(argv)

    if args.duration_seconds < 1:
        parser.error("--duration-seconds must be greater than 0")
    if not args.seed_url:
        parser.error("at least one --seed-url is required for manual-seed Phase 1")
    return args


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_id = args.run_id or f"{timestamp}-{slugify(args.topic)}"
    output_dir = Path(args.output_dir).resolve()
    run_dir = output_dir / run_id

    if run_dir.exists() and not args.force:
        print(f"Run directory already exists: {run_dir}", file=sys.stderr)
        print("Use --force to overwrite.", file=sys.stderr)
        return 1

    run_dir.mkdir(parents=True, exist_ok=True)

    sources = [build_source(url, index) for index, url in enumerate(args.seed_url, start=1)]
    package = build_package(args, run_id, sources)
    created_at = utc_now_iso()

    manifest = {
        "run_id": run_id,
        "created_at": created_at,
        "source_mode": "manual_seed",
        "status": "needs_review",
        "paths": {
            "production_package": "production-package.json",
            "brief": "brief.json",
            "sources": "sources.json",
            "qa": "08-qa.md",
        },
        "next_actions": [
            "Enrich research with youtube-market-research.",
            "Analyze source videos with youtube-video-analysis.",
            "Build claim ledger with youtube-fact-check.",
            "Draft script plan with youtube-script-architect.",
        ],
    }

    write_json(run_dir / "manifest.json", manifest)
    write_json(run_dir / "brief.json", package["brief"])
    write_json(run_dir / "sources.json", sources)
    write_json(run_dir / "production-package.json", package)
    write_markdown_files(run_dir, package)

    print(f"Created run: {run_id}")
    print(f"Run directory: {run_dir}")
    print(f"Source videos: {len(sources)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
